services:
  - type: web
    name: prompt2course-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn prompt2course.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prompt2course-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: prompt2course-db
    databaseName: prompt2course
    user: prompt2course
