# Generated by Django 5.2.3 on 2025-06-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
        migrations.AddField(
            model_name='course',
            name='course_data',
            field=models.JSONField(default=dict, help_text='Complete course content including lessons and quizzes'),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.CharField(default='hariprasadmanoj3', help_text='User who created the course', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='generating', help_text='Current status of the course generation', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='topic',
            field=models.CharField(help_text='The topic of the course', max_length=200),
        ),
        migrations.DeleteModel(
            name='CourseGenerationLog',
        ),
    ]
