from django.db import models
from django.utils import timezone

class Course(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    topic = models.CharField(max_length=200)
    content = models.TextField(blank=True, default='')
    created_by = models.CharField(max_length=100, default='hariprasadmanoj3')
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_at']
        db_table = 'courses_course'  # Explicitly set table name
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        # Auto-generate content if not provided
        if not self.content:
            self.content = f"""# {self.title}

## Course Overview
{self.description}

## Learning Objectives
- Master the fundamentals of {self.topic}
- Apply practical knowledge through hands-on exercises
- Build real-world projects
- Understand industry best practices

## Course Modules

### Module 1: Introduction to {self.topic}
- Overview and basic concepts
- Setting up your environment
- Getting started with fundamentals

### Module 2: Core Concepts
- Deep dive into key principles
- Practical examples and exercises
- Common patterns and techniques

### Module 3: Advanced Topics
- Advanced concepts and techniques
- Best practices and optimization
- Real-world applications

### Module 4: Hands-on Projects
- Project-based learning
- Portfolio development
- Industry case studies

## Resources and Next Steps
- Additional reading materials
- Community resources
- Recommended learning paths

---
*Course generated by AI on {timezone.now().strftime('%Y-%m-%d %H:%M:%S')} UTC*
*Created by: {self.created_by}*
"""
        super().save(*args, **kwargs)