from django.db import models
from django.utils import timezone

class Course(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    topic = models.CharField(max_length=200)
    content = models.TextField(blank=True, null=True)
    created_by = models.CharField(max_length=100, default='hariprasadmanoj3')
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-created_at']
    
    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        # Auto-generate content if not provided
        if not self.content:
            self.content = f"""
# {self.title}

## Course Overview
{self.description}

## Learning Objectives
- Understand the fundamentals of {self.topic}
- Apply practical knowledge through hands-on exercises
- Build real-world projects
- Master best practices and industry standards

## Course Modules

### Module 1: Introduction
- Overview and setup
- Basic concepts
- Getting started

### Module 2: Core Concepts
- Deep dive into fundamentals
- Practical examples
- Common patterns

### Module 3: Advanced Topics
- Advanced techniques
- Best practices
- Real-world applications

### Module 4: Projects
- Hands-on projects
- Portfolio development
- Industry case studies

## Resources
- Documentation links
- Additional reading
- Community resources

---
*Course generated by AI on {timezone.now().strftime('%Y-%m-%d %H:%M:%S')} UTC*
*Created by: {self.created_by}*
            """.strip()
        
        super().save(*args, **kwargs)